<a href="https://colab.research.google.com/github/kitaezzzza/psfp5/blob/main/simple_1_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Анализ данных с использованием библиотеки NumPy

## Создание массивов
1. Создайте одномерный массив из 10 случайных чисел.

2. Создайте двумерный массив размером 3x3, содержащий случайные числа.

3. Создайте массив с числами от 1 до 20 включительно с шагом 2.


In [ ]:
A = np.random.randint(0, 10, [1,10])
print(A)

[[5 8 4 9 3 0 5 2 5 4]]


In [ ]:
B = np.random.randint(0, 10,[3,3])
print(B)

[[0 8 9]
 [0 9 1]
 [1 2 6]]


In [ ]:
C = np.arange(1,20,2)
print(C)

[ 1  3  5  7  9 11 13 15 17 19]



## Информация о массиве
4. Выведите форму (размер) массива из задачи 2, используя атрибут `shape`.

5. Определите тип данных элементов массива из задачи 3, используя атрибут `dtype`.


In [ ]:
np.shape(B)

(3, 3)


## Операции с массивами
6. Умножьте каждый элемент массива из задачи 1 на 3.

7. Посчитайте сумму элементов массива из задачи 2 по каждой оси, используя функцию `np.sum()`.


In [ ]:
Y = A*3
print(Y)

[[ 9 12 24 24 21 15 15 12 15  9]]


In [ ]:
S = np.sum(B)
print(S)

49



## Индексация и срезы
8. Получите элемент из середины массива из задачи 1.

9. Выделите подматрицу размером 2x2 из массива задачи 2.


In [ ]:
m = a[0, A.shape[1] // 2]

print(m)

3


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


## Статистика и агрегация
10. Найдите среднее значение всех элементов массива из задачи 1, используя функцию `np.mean()`.

11. Найдите максимальное значение в каждой строке массива из задачи 2, используя функцию `np.max()`.


In [ ]:
X = np.mean(A)
print(X)

5.2


In [ ]:
Z = np.max(B)
print(Z)

8



## Логические операции
12. Создайте логический массив, проверяющий, какие элементы массива из задачи 1 больше 5.

13. Получите только те элементы массива из задачи 3, которые делятся на 3 без остатка.


In [ ]:
V = A>5
print(V)

[[False False  True  True  True False False False False False]]


In [ ]:
z = C/3
print(z)

[0.33333333 1.         1.66666667 2.33333333 3.         3.66666667
 4.33333333 5.         5.66666667 6.33333333]



## Работа с формой массива
14. Преобразуйте одномерный массив из задачи 1 в двумерный массив размером 2x5, используя метод `reshape()`.

15. Транспонируйте массив из задачи 2, используя метод `T`.


In [ ]:
F = np.reshape(A,[2,5])
print(F)

[[3 4 8 8 7]
 [5 5 4 5 3]]



## Сортировка и индексация
16. Отсортируйте элементы массива из задачи 1 по убыванию, используя функцию `np.sort()`.

17. Найдите индексы минимальных значений в каждом столбце массива из задачи 2, используя функцию `np.argmin()`.


In [ ]:
a = np.sort(-A)
print(-a)

[[9 8 5 5 5 4 4 3 2 0]]


In [ ]:
b = np.argmin(B)
print(b)

3



## Уникальные значения
18. Найдите уникальные значения в массиве из задачи 1, используя функцию `np.unique()`.

19. Посчитайте количество повторяющихся элементов в массиве из задачи 3, используя функцию `np.bincount()`.


In [ ]:
c = np.unique(A)
print(c)

[0 1 2 3 4 5 8]


In [ ]:
d = np.bincount(C)
print(d)

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]



## Линейная алгебра
20. Выполните матричное умножение двух массивов размером 3x3 из задачи 2, используя функцию `np.dot()`.

21. Решите систему линейных уравнений: `2x + y = 8` и `3x - y = 1`, используя функцию `np.linalg.solve()`.


In [ ]:
h = np.dot(B,B)
print(h)

[[ 9 90 62]
 [ 1 83 15]
 [ 6 38 47]]



## Векторизация
22. Создайте функцию, которая принимает на вход массив и возвращает новый массив, содержащий квадраты элементов входного массива.

23. Примените функцию из задачи 22 к массиву из задачи 1 с использованием векторизации.


In [ ]:
j = np.random.randint(0, 10, [1,10])
J = j**2
print(J)

[[ 4  9 81 16  9  1 64 64 16 36]]


In [ ]:
l = A**2
print(l)

[[16  4 16 16 64  4  9 25  1  0]]



## Статистика
24. Посчитайте медиану элементов массива из задачи 1, используя функцию `np.median()`.

25. Найдите стандартное отклонение значений в каждой строке массива из задачи 2, используя функцию `np.std()`.

In [ ]:
L = np.median(A)
print(L)

3.5


In [ ]:
N = np.std(B)
print(N)

1.640535895581489
