<a href="https://colab.research.google.com/github/kitaezzzza/psfp5/blob/main/simple_1_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# Анализ данных с использованием библиотеки NumPy

## Создание массивов
1. Создайте одномерный массив из 10 случайных чисел.

2. Создайте двумерный массив размером 3x3, содержащий случайные числа.

3. Создайте массив с числами от 1 до 20 включительно с шагом 2.


In [18]:
A = np.random.randint(0, 10, [1,10])
print(A)

[[1 3 6 8 3 5 5 8 6 8]]


In [6]:
B = np.random.randint(0, 10,[3,3])
print(B)

[[6 0 3]
 [2 7 6]
 [8 3 2]]


In [9]:
C = np.arange(0,21,2)
print(C)

[ 0  2  4  6  8 10 12 14 16 18 20]



## Информация о массиве
4. Выведите форму (размер) массива из задачи 2, используя атрибут `shape`.

5. Определите тип данных элементов массива из задачи 3, используя атрибут `dtype`.


In [10]:
U = np.shape(B)
print(U)

(3, 3)


## Операции с массивами
6. Умножьте каждый элемент массива из задачи 1 на 3.

7. Посчитайте сумму элементов массива из задачи 2 по каждой оси, используя функцию `np.sum()`.


In [19]:
Y = A*3
print(Y)

[[ 3  9 18 24  9 15 15 24 18 24]]


In [20]:
S = np.sum(B)
print(S)

37



## Индексация и срезы
8. Получите элемент из середины массива из задачи 1.

9. Выделите подматрицу размером 2x2 из массива задачи 2.


In [21]:
m = A[0, A.shape[1] // 2]

print(m)

5



## Статистика и агрегация
10. Найдите среднее значение всех элементов массива из задачи 1, используя функцию `np.mean()`.

11. Найдите максимальное значение в каждой строке массива из задачи 2, используя функцию `np.max()`.


In [22]:
X = np.mean(A)
print(X)

5.3


In [23]:
Z = np.max(B)
print(Z)

8



## Логические операции
12. Создайте логический массив, проверяющий, какие элементы массива из задачи 1 больше 5.

13. Получите только те элементы массива из задачи 3, которые делятся на 3 без остатка.


In [24]:
V = A>5
print(V)

[[False False  True  True False False False  True  True  True]]


In [25]:
z = C/3
print(z)

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.         6.66666667]



## Работа с формой массива
14. Преобразуйте одномерный массив из задачи 1 в двумерный массив размером 2x5, используя метод `reshape()`.

15. Транспонируйте массив из задачи 2, используя метод `T`.


In [26]:
F = np.reshape(A,[2,5])
print(F)

[[1 3 6 8 3]
 [5 5 8 6 8]]



## Сортировка и индексация
16. Отсортируйте элементы массива из задачи 1 по убыванию, используя функцию `np.sort()`.

17. Найдите индексы минимальных значений в каждом столбце массива из задачи 2, используя функцию `np.argmin()`.


In [29]:
a = np.sort(-A)
print(-a)

[[8 8 8 6 6 5 5 3 3 1]]


In [30]:
b = np.argmin(B)
print(b)

1



## Уникальные значения
18. Найдите уникальные значения в массиве из задачи 1, используя функцию `np.unique()`.

19. Посчитайте количество повторяющихся элементов в массиве из задачи 3, используя функцию `np.bincount()`.


In [32]:
c = np.unique(A)
print(c)

[1 3 5 6 8]


In [33]:
d = np.bincount(C)
print(d)

[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]



## Линейная алгебра
20. Выполните матричное умножение двух массивов размером 3x3 из задачи 2, используя функцию `np.dot()`.

21. Решите систему линейных уравнений: `2x + y = 8` и `3x - y = 1`, используя функцию `np.linalg.solve()`.


In [35]:
h = np.dot(B,B)
print(h)

[[60  9 24]
 [74 67 60]
 [70 27 46]]


In [42]:
y = np.linalg.solve([2x + y = 8], [3x - y = 1])
print(y)

SyntaxError: invalid decimal literal (<ipython-input-42-645af70a74b0>, line 1)


## Векторизация
22. Создайте функцию, которая принимает на вход массив и возвращает новый массив, содержащий квадраты элементов входного массива.

23. Примените функцию из задачи 22 к массиву из задачи 1 с использованием векторизации.


In [43]:
j = np.random.randint(0, 10, [1,10])
J = j**2
print(J)

[[49  1  9 49  9 81 36 36 64  9]]


In [44]:
l = A**2
print(l)

[[ 1  9 36 64  9 25 25 64 36 64]]



## Статистика
24. Посчитайте медиану элементов массива из задачи 1, используя функцию `np.median()`.

25. Найдите стандартное отклонение значений в каждой строке массива из задачи 2, используя функцию `np.std()`.

In [45]:
L = np.median(A)
print(L)

5.5


In [46]:
N = np.std(B)
print(N)

2.5579698740491863
